# Generated by Django 3.2.8 on 2022-02-21 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testajax', '0005_alter_blog_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
