# Generated by Django 3.2.8 on 2022-02-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testajax', '0006_alter_blog_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription',
            field=models.TextField(),
        ),
    ]
