# Generated by Django 3.2.8 on 2022-02-23 10:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testajax', '0013_alter_task_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dis',
            field=ckeditor.fields.RichTextField(default=2),
        ),
    ]
