# Generated by Django 3.2.8 on 2022-02-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220211_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_type',
            new_name='label',
        ),
    ]
