# Generated by Django 3.2.8 on 2022-02-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220211_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImg'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='ProductImg/noimg.jpg', upload_to='ProductImg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('offer', 'Offer'), ('StockOut', 'Stock Out')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Feature', 'Feature'), ('OneSale', 'OneSale'), ('TopRate', 'TopRate')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SaleType',
        ),
    ]
