# Generated by Django 3.2.8 on 2022-02-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220211_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, default='ProductImg/noimgs.jpg', null=True, upload_to='ProductImg'),
        ),
    ]
