# Generated by Django 3.2.8 on 2022-02-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220213_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='ProductImg/noimg.jpg', upload_to='brandImg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImg'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(upload_to='CategoryImg'),
        ),
    ]
