# Generated by Django 3.2.8 on 2022-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Caro', 'Caro'), ('first_p_add', 'first_p_add'), ('second_p_add', 'second_p_add')], default='Caro', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, default='noimg.jpg', null=True, upload_to='ProductImg'),
        ),
    ]
