# Generated by Django 3.2.8 on 2022-02-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220213_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productcategory'),
        ),
    ]
