# Generated by Django 3.2.8 on 2022-02-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220216_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.productcategory'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoris',
        ),
        migrations.AddField(
            model_name='product',
            name='categoris',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.productcategory', verbose_name='Product Category'),
        ),
    ]
