# Generated by Django 3.2.8 on 2022-02-18 04:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_productcategory_top_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
