# Generated by Django 3.2.8 on 2022-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variation',
            field=models.ManyToManyField(to='store.VariationValue'),
        ),
    ]
