# Generated by Django 3.2.8 on 2022-03-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_rename_product_whishlist_wish_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishlist',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
