# Generated by Django 3.2.8 on 2022-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_order_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiping_charge',
            field=models.IntegerField(default=60),
        ),
    ]
