# Generated by Django 3.2.8 on 2022-03-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0003_billingaddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
