# Generated by Django 3.2.8 on 2022-03-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0004_alter_billingaddress_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'BillingAddress'},
        ),
    ]
