# Generated by Django 3.2.8 on 2022-02-21 20:08

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testajax', '0008_alter_blog_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription',
            field=django_quill.fields.QuillField(),
        ),
    ]
