# Generated by Django 3.2.8 on 2022-02-23 10:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testajax', '0011_auto_20220223_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dis',
            field=ckeditor.fields.RichTextField(default=2),
        ),
    ]
