# Generated by Django 3.2.8 on 2022-02-23 10:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testajax', '0012_task_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dis',
            field=django_quill.fields.QuillField(),
        ),
    ]
