# Generated by Django 3.2.8 on 2022-03-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0002_alter_billingaddress_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default='a', max_length=150),
        ),
    ]
