# Generated by Django 3.2.8 on 2022-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(default='CategoryImg/noimg.jpg', upload_to='CategoryImg')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('product_color', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=150)),
                ('sort_discription', models.TextField()),
                ('discription', models.TextField()),
                ('aditional_discription', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('categoris', models.ManyToManyField(to='store.ProductCategory', verbose_name='Product Category')),
            ],
        ),
    ]
