# Generated by Django 3.2.8 on 2022-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220211_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labal',
        ),
        migrations.AlterField(
            model_name='product',
            name='aditional_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
