# Generated by Django 3.2.8 on 2022-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_hover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Offer', 'Offer'), ('Out', 'Out')], max_length=50, null=True),
        ),
    ]
