# Generated by Django 3.2.8 on 2022-02-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220212_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='top_category',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
