# Generated by Django 3.2.8 on 2022-02-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20220216_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcategory', verbose_name='Product Category'),
        ),
    ]
