# Generated by Django 3.2.8 on 2022-02-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_categoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='top_category',
        ),
    ]
