# Generated by Django 3.2.8 on 2022-02-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_variationvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvalue',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
