# Generated by Django 3.2.8 on 2022-02-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20220227_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
    ]
