# Generated by Django 3.2.8 on 2022-02-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variation',
        ),
    ]
