# Generated by Django 3.2.8 on 2022-02-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20220228_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
