# Generated by Django 3.2.8 on 2022-03-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0002_alter_billingaddress_order_note'),
        ('store', '0042_whishlist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentApp.billingaddress'),
        ),
    ]
