# Generated by Django 3.2.8 on 2022-03-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20220316_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='PaymentType',
            new_name='payment_type',
        ),
    ]
