# Generated by Django 3.2.8 on 2022-03-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_rename_paymenttype_paymenttype_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
