# Generated by Django 3.2.8 on 2022-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('SSL Commerce', 'SSL Commerce'), ('Stripe', 'Stripe'), ('PayPal', 'PayPal')], default='Cash On Delivery', max_length=150),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
