# Generated by Django 3.2.8 on 2022-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_order_shiping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
